### ISSUE TITLE
src/components/Todo/Todo.css 질문

### ISSUE THREAD

**Issue by kanghc0217** [ktaebum/swpp-react-tutorial#1]
안녕하세요 조교님, react tutorial에서 css 질문이 있습니다!
src/components/Todo/Todo.css 이 코드를 보면 중간에

text라는 클래스와 done이라는 클래스가 보이는데,
혹시 각 클래스가 Todo.js의 ```<div className={`text ${this.props.done && "done"}`}>...</div>```
의 ```{`text ${this.props.done && "done"}`}``` 때문에 만들어진거라면 이해가 잘 되지 않습니다.

console log로 해당 부분의 class 명을 읽어보았는데,
'text done'이거나 'text false' 였습니다.

즉, text라는 클래스와 done이라는 클래스는 없는데,
css가 어떻게 동작을 한건가요?

**Comment by ktaebum** [comment]
엇 여기에 질문을 하셨군요 우선 수업 관련 질문은 여기 말고 공식 레포를 이용해주세요 :)

질문에 대한 답변은 https://github.com/swsnu/swppfall2019/issues/47에 적어두겠습니다!

**Comment by kanghc0217** [comment]
앗. 다음 질문도 옮겨두겠습니다.
